service: lambda-qraphql

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1

plugins:
    - serverless-webpack

package:
    individually: true

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: lambdas/graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: srkica-2323
