service: lambda-qraphql-srkica232323

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-offline
  #- serverless-webpack

custom:
  serverless-offline:
    allowCache: true

  #webpack:
    #webpackConfig: "webpack.config.js"
    i#ncludeModules: true

package:
  #individually: true
  exclude:
    - "./node_modules/**"
    #- "./webpack.config.js"

functions:
  graphql:
    handler: lambdas/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: ANY
          cors: true    
