service: lambda-qraphql-webpack

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-s3-sync

custom:
  serverless-offline:
    allowCache: true
  s3Sync:
    - bucketName: srdjan23
      localDir: UploadData
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

package:
    individually: true

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: lambdas/graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: POST
        cors: true
    - http:
        path: graphql
        method: GET
        cors: true
    - http:
        path: playground
        method: ANY
        cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: srdjan23