service: lambda-serverless-back

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

package:
  exclude:
    - "./node_modules/**"
  
functions:
  graphql:
    handler: lambdas/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: ANY
          cors: true    
